name: 💡 Discussion or Idea
description: Discussion or Idea request
title: "<title>"
labels: [discuss, idea, question]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the idea you want to submit.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Summary
    description: Please provide a summary for the discussion or idea request
    placeholder: ex. I think a really good idea would be ...
  validations:
    required: false
- type: textarea
  attributes:
    label: What Issue Are We Solving?
    description: Give a detailed descriptions of the task we are trying to solve.
  validations:
    required: false
- type: textarea
  attributes:
    label: Examples
    description: Any examples of this being done elsewhere?
  validations:
    required: false
- type: textarea
  attributes:
    label: External Resources
    description: Links to external resources
  validations:
    required: false    
- type: textarea
  attributes:
    label: Additional Context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false    
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
